Hydrogen is incompatible with Optifine/Optifabric; make this combo illegal
CaffeineMC/hydrogen-fabric pull request #45
Opened 2021-06-22 23:40 UTC by MeeniMc

Make explicit the fact that Hydrogen and Optifine/Optifabric don't mix well.

2021-06-23 16:20 UTC, arceuss commented
inb4 people still make issues about both not working together

2021-06-23 16:46 UTC, RDKRACZ commented
This won't help in all cases as some people don't understand what "found conflicting mods" mean.
https://github.com/Gegy/tic-tacs/issues/43

2021-06-23 16:48 UTC, jellysquid3 requested changes

2021-06-23 16:48 UTC, jellysquid3 commented on gradle.properties
> +mod_version=0.3.1
Please don't bump versions in PRs.

2021-06-23 18:10 UTC, MeeniMc commented on gradle.properties
> +mod_version=0.3.1
Ok, I'll force push to remove this

2021-06-25 03:56 UTC, l1ving approved these changes

2021-07-15 18:45 UTC, jellysquid3 approved these changes

2021-07-15 18:46 UTC, merged